enum konsulenterActionTypes {
  REQUEST_START = "REQUEST_START",
  REQUEST_FAILED = "REQUEST_FAILED",
  HENT_KONSULENTER_SUCCESS = "HENT_KONSULENTER_SUCCESS",
  LEGG_TIL_KONSULENT_SUCCESS = "LEGG_TIL_KONSULENT_SUCCESS",
  SLETT_KONSULENT_SUCCESS = "SLETT_KONSULENT_SUCCESS",
}

export default konsulenterActionTypes;
