enum todosActionTypes {
  REQUEST_START = "REQUEST_START",
  REQUEST_FAILED = "REQUEST_FAILED",
  GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS",
  ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS",
  DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS",
  MODIFY_TODO_DONE_STATUS_SUCCESS = "MODIFY_TODO_DONE_STATUS_SUCCESS",
}

export default todosActionTypes;
